apiVersion: apps/v1
kind: Deployment
metadata:
  name: retriever
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retriever
  template:
    metadata:
      labels:
        app: retriever
    spec:
      containers:
      - name: retriever
        image: JuliaWPereira/embedder:latest
        ports:
        - containerPort: 5000
        
---
          
apiVersion: v1
kind: Service
metadata:
  name: svc-retriever
spec:
  type: ClusterIP
  selector:
    app: retriever
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

