apiVersion: apps/v1
kind: Deployment
metadata:
  name: embedder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embedder
  template:
    metadata:
      labels:
        app: embedder
    spec:
      containers:
      - name: embedder
        image: atopredictcontainerregistry.azurecr.io/atopredict/asp-assistant:v0.0.4
        ports:
        - containerPort: 5000
        
---
          
apiVersion: v1
kind: Service
metadata:
  name: svc-embedder
spec:
  type: ClusterIP
  selector:
    app: embedder
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

